
# resume information
resume-index = 62570
seed = 6128130976510555874
rate = 1000      
shard = 1/1
nocapture = servername

output-filename = /tmp/kali_scan_outputs/http___testphp_vulnweb_com__20250926_140642/masscan_raw_output.json
output-format = json

adapter-ip = 10.0.2.15
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 1-65535
range = 44.228.249.3

